In [1]:
import numpy as np

#1- Write a NumPy program to test whether none of the elements of a given array is zero.

In [4]:
arr_1=np.array([1,2,3,4,5])
test=arr_1.all()

print(test)

True


In [5]:
arr_1=np.array([0,1,2,3,4,5])
test=arr_1.all()

print(test)

False


#2- Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [8]:
arr_1=np.array([0,0,3,0,0])
test=arr_1.any()

print(test)

True


In [9]:
arr_1=np.array([0,0,0,0,0])
test=arr_1.any()

print(test)

False


#3- Write a NumPy program to create an element-wise comparison (equal,equal within a tolerance) of two given

In [23]:
arr_1=np.array([1,2,3,4,5,6,7,8,9,10])
arr_2=np.array([1,2,3,4,5,6,7,8,9,10.0001])
arr_3=np.array([1,2,3,4,5,6,7,8,9,11])

print("Comparison - equal:")
print(f'arr_1,arr_2: {np.equal(arr_1,arr_2)}')
print(f'arr_1,arr_3: {np.equal(arr_1,arr_3)}')

print("\nComparison - equal within a tolerance:")
print(f'arr_1,arr_2: {np.allclose(arr_1,arr_2)}')
print(f'arr_1,arr_3: {np.allclose(arr_1,arr_3)}')


Comparison - equal:
arr_1,arr_2: [ True  True  True  True  True  True  True  True  True False]
arr_1,arr_3: [ True  True  True  True  True  True  True  True  True False]

Comparison - equal within a tolerance:
arr_1,arr_2: True
arr_1,arr_3: False


#4- Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [28]:
arr_1= np.zeros(10)
print(arr_1)

arr_1= np.ones(10)
print(arr_1)

arr_1= np.ones(10)*5
print(arr_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#5- Write a NumPy program to create an array of the integers from 30 to 70.

In [31]:
arr_1=np.arange(30,71)
print(arr_1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


#6- Write a NumPy program to create a 3x3 identity matrix.

In [37]:
arr_1=np.identity(3)
print(arr_1)

arr_1=np.eye(3)
print(f'\n {arr_1}')

arr_1=np.eye(3,3)
print(f'\n {arr_1}')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#7- Write a NumPy program to generate a random number between 0 and 1.

In [62]:
arr_1=np.random.randint(0,2)
print(arr_1)

1


#8- Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [70]:
arr_1=np.random.normal(0,2,15)
print(arr_1)

arr_1=np.random.standard_normal(15)
print(f'\n {arr_1}')

[ 4.38192967  1.0210943   3.28000775 -0.11614394  0.08848017  1.99183116
  2.32931131  0.84003421 -2.1802952   0.73856018 -2.09281025  0.55846377
 -2.69713353  0.89736607  1.65966863]

 [ 1.32694273 -0.35547325  2.27128577  0.94535644  0.76934947 -1.41229014
 -0.21679626 -1.59489942  0.86663068 -2.13549179 -1.47049531 -0.19235083
 -2.51432932  0.62103655  0.7298401 ]


#9- Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [81]:
arr_1=np.arange(15,56)
print(arr_1[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


#10- Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [82]:
arr_1=np.random.randint(0,11,5)
print(arr_1)

[5 1 2 6 7]


#11- Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [87]:
arr_1=np.ones((10,10))
arr_1[1:-1,1:-1]=0
print(arr_1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#12- Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1,2,3,4,5.

In [113]:
arr_1=np.diag((1,2,3,4,5))
print(arr_1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#13- Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [125]:
arr_1=np.zeros((4,4))
arr_1[1::2,::2]=1
arr_1[::2,1::2]=1
print(arr_1)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


#14- Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.

In [149]:
arr_1=np.array([1,2,3,4,5])
print(arr_1)
arr_2=np.array([6,7,8,9])
print(arr_2)

np.savez('arrays.npz',x=arr_1,y=arr_2)

with np.load('arrays.npz') as arrays:
  arr_3=arrays['x']
  arr_4=arrays['y']

print(f'Loaded arrays: \n{arr_3}\n{arr_4}')

[1 2 3 4 5]
[6 7 8 9]
Loaded arrays: 
[1 2 3 4 5]
[6 7 8 9]


#15- Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.

In [200]:
np.random.seed(3)
arr_1=np.random.rand(40)
print(arr_1)

[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695 0.89629309
 0.12558531 0.20724288 0.0514672  0.44080984 0.02987621 0.45683322
 0.64914405 0.27848728 0.6762549  0.59086282 0.02398188 0.55885409
 0.25925245 0.4151012  0.28352508 0.69313792 0.44045372 0.15686774
 0.54464902 0.78031476 0.30636353 0.22195788 0.38797126 0.93638365
 0.97599542 0.67238368 0.90283411 0.84575087 0.37799404 0.09221701
 0.6534109  0.55784076 0.36156476 0.2250545 ]


#16- Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [210]:
arr_1=np.array([1,2,3,4,5,6,7,8,9])
arr_1[arr_1>3]
print(arr_1[arr_1>3])
print(arr_1[arr_1<7])

[4 5 6 7 8 9]
[1 2 3 4 5 6]
